### ISSUE TITLE
Error launching nibble in a new installation (Windows)

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/adaptive-tools-nibble#12]
Just installed using the following command:

`npm i npm-adaptiveme-nibble -g`

And tried to launch with the following command:

`nibble -p http://google.com`

it looks like even though I have passed an URL it's expecting a file

**Caused by: java.lang.IllegalArgumentException: C:\mobile\Web\WebResources\www\http:\google.com**

and the error:

```
Launching: AbstractDevice{deviceVendor='Apple', deviceType='Mobile', deviceName='iPhone', deviceModel='6Plus'} With: AbstractOs{osName='iOS', osVersion='8.0', osVendor='Apple', osType=Mobile}
jul 23, 2015 1:22:37 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: C:\mobile\Web\WebResources\www\http:\google.com
    at org.eclipse.jetty.server.handler.ResourceHandler.setResourceBase(ResourceHandler.java:213)
    at me.adaptive.tools.nibble.common.AbstractOsController.initializeAdaptiveBridge(AbstractOsController.java:257)
    at me.adaptive.tools.nibble.common.AbstractOsController.setParentDeviceController(AbstractOsController.java:544)
    at me.adaptive.tools.nibble.emulator.Nibble.launchDefault(Nibble.java:214)
    at me.adaptive.tools.nibble.emulator.Nibble.start(Nibble.java:366)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$172(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$147(Unknown Source)
    ... 1 more
usage: nibble [-a <apiVersion>] [-d <id>] [-h] [-l <type>] [-p <path>] [-v] [-w <boolean>]
Parameters:
 -a,--api <apiVersion>    Adaptive API level to emulate.
                          Default: 2.2.0
 -d,--device <id>         Launch emulator with given device id (id retrieved from --list option).
                          Default: Will launch a cool smartphone.
 -h,--help                Print help usage message message.
 -l,--list <type>         List devices for type [all, generic, wearable, smartphone, tablet, browser, desktop, television].
                          Default: all
 -p,--path <path>         Launch emulator with given path (http://<url> or <localpath>/index.html).
                          Example: app/index.html , http://google.com
 -v,--version             Print current version and exit.
 -w,--watcher <boolean>   Watch local resources and reload emulator on changes.
                          Default: false
AdaptiveMe Nibble 1.0-rc.1 - Forged with ? in Barcelona. �2013-2015 adaptive.me / Carlos Lozano Diez.
ERROR: Unsupported parameters.
[nibble] Error running the emulator. Exiting

```

**Comment by carloslozano** [comment]
ERROR: Unsupported parameters?
